name: super_enum
description: Create super-powered enums similar to sealed classes in Kotlin.
version: 1.0.0
homepage: https://github.com/Octacore19/super_enum

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: '>=1.3.0 <1.5.0'
  equatable: ^2.0.3

# Adding dev dependencies
# just for showcasing an example
dev_dependencies:
  http: ^0.13.3
  build_runner: ^2.0.5
  super_enum_generator:
    path: ../super_enum_generator

